theme: jekyll-theme-minimal
lang: ja-JP
# Defaults
defaults:
  # _posts
  - scope:
      path          : ""
      type          : pages
    values:
      layout        : single
      classes       : wide
      author_profile: false
      read_time     : false
      comments      : false
      share         : false
      related       : true
